# Generated by Django 5.1.6 on 2025-04-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lef2', '0003_customuser_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
