# Generated by Django 5.1.7 on 2025-04-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lef2', '0004_remove_customuser_phone_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
