# Generated by Django 5.1.7 on 2025-05-17 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lef2', '0007_alter_event_options_event_category_alter_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='End Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='organizer_name',
            field=models.CharField(default='Unknown Organizer', max_length=100, verbose_name='Organizer Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Start Time'),
            preserve_default=False,
        ),
    ]
