# Generated by Django 5.1.7 on 2025-05-17 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lef2', '0009_alter_event_options_remove_event_organizer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='package_price',
            new_name='packages',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='organizer_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='book_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='slots',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('tech', 'Tech'), ('food', 'Food')], default='music', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
