# Generated by Django 5.1.7 on 2025-05-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lef2', '0010_rename_package_price_event_packages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AlterField(
            model_name='event',
            name='book_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event_images/host.jpg', upload_to='event_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
