# Generated by Django 5.1.7 on 2025-05-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lef2', '0011_remove_event_category_alter_event_book_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event_images/host.jpg', upload_to='event_images/'),
        ),
    ]
