# Generated by Django 5.1.7 on 2025-05-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lef2', '0012_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('food', 'Food'), ('art', 'Art'), ('games', 'Games'), ('tech', 'Tech')], default='music', max_length=50),
        ),
    ]
