# Generated by Django 5.1.7 on 2025-05-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lef2', '0013_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='book_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
