# Generated by Django 5.1.7 on 2025-05-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lef2', '0014_alter_event_book_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_upcoming',
            field=models.BooleanField(default=True),
        ),
    ]
