# Generated by Django 5.1.7 on 2025-07-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lef2', '0018_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
